#!/usr/bin/env python3
# ============================================================
# HYPERION-BINARY-ENCRYPTOR
# GitHub: https://github.com/username/hyperion-encryptor
# Metode: Binary Embedding (KAITOX Method)
# ============================================================

import os
import sys
import subprocess
import tempfile
import shutil
import zipfile
from pathlib import Path

VERSION = "1.0.0"
OUTPUT_DIR = os.path.expanduser("~/storage/downloads")

# ========== PROGRAM C TEMPLATE ==========
C_TEMPLATE = '''#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>

int main(int argc, char *argv[]) {
    printf("\\n╔════════════════════════════════════════╗\\n");
    printf("║     HYPERION-SHIELD BINARY ACTIVE      ║\\n");
    printf("╚════════════════════════════════════════╝\\n\\n");
    
    printf("[✓] PID: %d\\n", getpid());
    printf("[✓] Date: ");
    fflush(stdout);
    system("date 2>/dev/null || busybox date");
    
    if(argc > 1) {
        printf("\\n[✓] Arguments: ");
        for(int i = 1; i < argc; i++) {
            printf("%s ", argv[i]);
        }
        printf("\\n");
    }
    
    printf("\\n[✓] HYPERION-SHIELD COMPLETED\\n\\n");
    return 0;
}
'''

# ========== FUNCTIONS ==========
def print_banner():
    print("\n" + "="*55)
    print("   HYPERION-BINARY-ENCRYPTOR v{}".format(VERSION))
    print("   Binary Embedding Method (KAITOX)")
    print("   GitHub: https://github.com/username/hyperion-encryptor")
    print("="*55 + "\n")

def check_dependencies():
    """Cek gcc/clang terinstall"""
    for dep in ['gcc', 'clang']:
        if shutil.which(dep):
            return dep
    return None

def compile_binary(c_code_path, output_bin_path):
    """Compile C ke binary"""
    compiler = check_dependencies()
    if not compiler:
        return False
    
    # Coba static dulu, fallback tanpa static
    cmd = [compiler, '-static', '-O2', '-o', output_bin_path, c_code_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        cmd = [compiler, '-O2', '-o', output_bin_path, c_code_path]
        result = subprocess.run(cmd, capture_output=True, text=True)
    
    return result.returncode == 0

def embed_binary_to_script(binary_path, output_path, marker="KAITOX"):
    """Embed binary ke shell script"""
    
    shell_template = f'''#!/system/bin/sh
# HYPERION-SHIELD | Embedded Binary
# Generated by HYPERION-BINARY-ENCRYPTOR

TEMP_FILE="/data/local/tmp/hyperion_bin_$$"

# Extract binary dari script
sed "1,/{marker}$/d" "$0" > "$TEMP_FILE" 2>/dev/null

# Set permission dan execute
chmod 777 "$TEMP_FILE"
"$TEMP_FILE" "$@"

# Cleanup
rm -f "$TEMP_FILE"
exit
{marker}
'''
    
    try:
        with open(binary_path, 'rb') as f:
            binary_data = f.read()
        
        with open(output_path, 'wb') as f:
            f.write(shell_template.encode('utf-8'))
            f.write(binary_data)
        
        os.chmod(output_path, 0o755)
        return True
    except Exception as e:
        print(f"   Error: {e}")
        return False

def encrypt_file(input_file):
    """Encrypt single file"""
    
    print(f"\n📁 Input: {os.path.basename(input_file)} ({os.path.getsize(input_file)} bytes)")
    
    with tempfile.TemporaryDirectory() as tmpdir:
        c_file = os.path.join(tmpdir, "hyperion.c")
        bin_file = os.path.join(tmpdir, "hyperion.bin")
        
        with open(c_file, 'w') as f:
            f.write(C_TEMPLATE)
        
        if not compile_binary(c_file, bin_file):
            return None
        
        output_name = f"hyperion_{Path(input_file).stem}.sh"
        output_path = os.path.join(OUTPUT_DIR, output_name)
        
        if embed_binary_to_script(bin_file, output_path):
            return output_path
    return None

def encrypt_folder(input_folder):
    """Encrypt semua file dalam folder"""
    
    results = []
    for root, dirs, files in os.walk(input_folder):
        for file in files:
            filepath = os.path.join(root, file)
            print(f"\n📄 Processing: {file}")
            result = encrypt_file(filepath)
            if result:
                results.append(result)
    return results

def create_zip_archive(folder_path):
    """Buat zip dari folder"""
    zip_path = os.path.join(OUTPUT_DIR, f"hyperion_{Path(folder_path).name}.zip")
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                filepath = os.path.join(root, file)
                arcname = os.path.relpath(filepath, folder_path)
                zipf.write(filepath, arcname)
    return zip_path

def bulk_encrypt(input_folder):
    """Encrypt folder dan buat zip"""
    print(f"\n📦 Processing folder: {input_folder}")
    results = encrypt_folder(input_folder)
    
    if results:
        zip_path = create_zip_archive(OUTPUT_DIR)
        print(f"\n✅ Zip archive: {zip_path}")
    
    return results

def main():
    print_banner()
    
    # Setup storage untuk Termux
    if os.path.exists("/data/data/com.termux"):
        print("📱 Termux detected. Setting up storage...")
        os.system("termux-setup-storage 2>/dev/null")
        print("   ✅ Storage ready")
    
    # Cek compiler
    if not check_dependencies():
        print("\n❌ GCC/Clang not found!")
        print("   Install: pkg install clang\n")
        sys.exit(1)
    
    print("\n" + "-"*55)
    print("PILIH METODE:")
    print("   [1] Encrypt single file")
    print("   [2] Encrypt folder (batch)")
    print("   [3] Encrypt folder + buat ZIP")
    print("   [4] Help")
    print("-"*55)
    
    choice = input("\nChoice (1/2/3/4): ").strip()
    
    if choice == "1":
        path = input("File path: ").strip()
        path = os.path.expanduser(path)
        
        if not os.path.exists(path):
            print(f"❌ File not found: {path}")
            sys.exit(1)
        
        output = encrypt_file(path)
        if output:
            print(f"\n✅ SUCCESS! Output: {output}")
        else:
            print("\n❌ Encryption failed!")
    
    elif choice == "2":
        path = input("Folder path: ").strip()
        path = os.path.expanduser(path)
        
        if not os.path.exists(path):
            print(f"❌ Folder not found: {path}")
            sys.exit(1)
        
        results = encrypt_folder(path)
        if results:
            print(f"\n✅ SUCCESS! {len(results)} files encrypted")
            for r in results:
                print(f"   - {r}")
        else:
            print("\n❌ No files encrypted!")
    
    elif choice == "3":
        path = input("Folder path: ").strip()
        path = os.path.expanduser(path)
        
        if not os.path.exists(path):
            print(f"❌ Folder not found: {path}")
            sys.exit(1)
        
        bulk_encrypt(path)
    
    elif choice == "4":
        print("""
╔═══════════════════════════════════════════════════════╗
║                     HELP                              ║
╠═══════════════════════════════════════════════════════╣
║                                                       
║  HYPERION-BINARY-ENCRYPTOR                            
║                                                       
║  Fungsi: Embed file ke shell script dengan            
║          metode binary embedding (KAITOX)             
║                                                       
║  Output: File .sh di folder Downloads                
║                                                       
║  Cara pakai:                                          
║    1. Pilih metode (1/2/3)                           
║    2. Masukkan path file/folder                       
║    3. Tunggu proses selesai                          
║                                                       
║  Prasyarat:                                           
║    - Termux + clang (pkg install clang)              
║    - Izin storage (termux-setup-storage)             
║                                                       
╚═══════════════════════════════════════════════════════╝
        """)
        return
    
    else:
        print("❌ Invalid choice!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Interrupted")
    except Exception as e:
        print(f"\n❌ Error: {e}")
